### ISSUE TITLE
Genome build ?

### ISSUE THREAD

**Issue by lgmgeo** [ChildrensMercyResearchInstitute/GA4K#1]
Thank you very much for making your PacBio genome SV allele frequency reference publicly available.

Can you please indicate in the README the genome build? GRCh37 or GRCh38?
(It is not indicated in the VCF)

Thanks again,
Véronique

**Comment by wac** [comment]
the genome build for all the files is GRCh38 - I've added notes to all 3 READMEs.

**Comment by lgmgeo** [comment]
Thank you!!
